---
# defaults file for ansible-role-consul-install

consul_version: latest
consul_arch: linux_amd64
checkpoint_url: "https://checkpoint-api.hashicorp.com/v1/check/consul"
consul_dependencies:
  - unzip
consul_bin_path: "/usr/bin"
consul_path: "/opt/consul"
consul_conf: "{{ consul_path }}/consul_a.hcl"
consul_local_script: False
consul_datacenter: "dc1"
consul_user: "consul"
consul_group: "consul"
consul_service: "consul"
ansible_consul_group: "consul"
consul_servers: [consul_s1,consul_s2,consul_s3]

